version: '3.7'

services:
  db:
    build: 
      context: ../
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - my-network

  testing-be:
    build: 
      context: ../
    ports:
      - "3000:3000"
    networks:
      - my-network
    command: sh -c "sleep 3 && npm run test"
    depends_on:
      - db

networks:
  my-network:
    driver: bridge