name: Deployment API
on: workflow_dispatch
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependences
        run: npm ci
      - name: Linting check
        run: npm run lint
      - name: Finished
        run: echo "finished lint"
  testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependences
        run: npm ci
      - name: Run docker-compose
        run: docker compose -f ./testing/docker-compose.yml up --exit-code-from testing-be
      - name: Finished test
        run: echo "finished testing"
  building:
    needs: testing
    runs-on: ubuntu-latets
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependences
        run: npm ci
      - name: Start building
        run: npm run build
      - name: Finished build
        run: echo "finished build"
